FROM golang:1.12

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go get -d -v ./...

# Build executable
RUN go build -o bin/chubby chubby/cmd/*.go

# Run chubby exec
CMD ["bin/chubby", "-id", "node5", "-listen", ":9379", "-raftbind", ":19379", "-join", "localhost:5379"]