FROM golang:1.12

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go get -d -v ./...

# Build executable
RUN go build -o bin/client_fast_reqs chubby/cmd/client_fast_reqs.go

# Run simple_client exec
CMD ["bin/client_fast_reqs"]