FROM golang:1.12

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go get -d -v ./...

# Build executable
RUN go build -o chubby/acquire_lock_client chubby/cmd/acquire_Lock_Client.go

# Run simple_client exec
CMD ["chubby/acquire_lock_client"]
